import { v4 as uuid } from 'uuid';
import { Customer, StatusEnum } from './customer.model';

export default function customerSeed(): Array<Customer> {
  return [
    {
      id: uuid(),
      firstName: 'Juliana',
      lastName: 'Raybon',
      email: 'julianajraybon@jourrapide.com',
      status: StatusEnum.ACTIVE,
    },
    {
      id: uuid(),
      firstName: 'Kylie',
      lastName: 'Nelson',
      email: 'KylieCNelson@armyspy.com',
      status: StatusEnum.ACTIVE,
      phone: '573-885-6825',
    },
    {
      id: uuid(),
      firstName: 'Christian',
      lastName: 'Fuentes',
      email: 'christiantfuentes@teleworm.us',
      status: StatusEnum.PENDING,
      phone: '408-965-7232',
    },
    {
      id: uuid(),
      firstName: 'Laura',
      lastName: 'Cupp',
      email: 'LauraMCupp@teleworm.us',
      status: StatusEnum.INACTIVE,
    },
    {
      id: uuid(),
      firstName: 'Michael',
      lastName: 'Randolph',
      email: 'michaelkrandolph@armyspy.com',
      status: StatusEnum.ACTIVE,
    },
    {
      id: uuid(),
      firstName: 'Manuel',
      lastName: 'Baker',
      email: 'manuelcbaker@rhyta.com',
      status: StatusEnum.ACTIVE,
      phone: '830-376-9150',
    },
    {
      id: uuid(),
      firstName: 'Nancy',
      lastName: 'Hines',
      email: 'nancymhines@armyspy.com',
      status: StatusEnum.ACTIVE,
      phone: '708-808-7998',
    },
    {
      id: uuid(),
      firstName: 'Mary',
      lastName: 'Brown',
      email: 'maryebrown@dayrep.com',
      status: StatusEnum.ACTIVE,
      phone: '701-724-5656',
    },
    {
      id: uuid(),
      firstName: 'Ruby',
      lastName: 'Braddock',
      email: 'rubyrbraddock@armyspy.com',
      status: StatusEnum.INACTIVE,
    },
    {
      id: uuid(),
      firstName: 'Kent',
      lastName: 'Rodriguez',
      email: 'kentsrodriguez@jourrapide.com',
      status: StatusEnum.INACTIVE,
      phone: '415-524-4649',
    },
    {
      id: uuid(),
      firstName: 'Patricia',
      lastName: 'Elliott',
      email: 'patricianelliott@rhyta.com',
      status: StatusEnum.PENDING,
      phone: '507-834-9019',
    },
    {
      id: uuid(),
      firstName: 'Chester',
      lastName: 'Fisher',
      email: 'chesterdfisher@jourrapide.com',
      status: StatusEnum.ACTIVE,
    },
    {
      id: uuid(),
      firstName: 'James',
      lastName: 'Cooks',
      email: 'jamesdcooks@dayrep.com',
      status: StatusEnum.INACTIVE,
    },
    {
      id: uuid(),
      firstName: 'Timothy',
      lastName: 'Johnson',
      email: 'timothypjohnson@rhyta.com',
      status: StatusEnum.INACTIVE,
      phone: '770-752-8123',
    },
    {
      id: uuid(),
      firstName: 'Douglas',
      lastName: 'Thomas',
      email: 'douglassthomas@rhyta.com',
      status: StatusEnum.INACTIVE,
    },
    {
      id: uuid(),
      firstName: 'Reggie',
      lastName: 'Capone',
      email: 'reggiescapone@dayrep.com',
      status: StatusEnum.PENDING,
    },
    {
      id: uuid(),
      firstName: 'Robert',
      lastName: 'Wilde',
      email: 'robertvwilde@jourrapide.com',
      status: StatusEnum.PENDING,
      phone: '407-235-9104',
    },
    {
      id: uuid(),
      firstName: 'Christopher',
      lastName: 'Huber',
      email: 'christopherchuber@rhyta.com',
      status: StatusEnum.ACTIVE,
      phone: '949-851-6640',
    },
    {
      id: uuid(),
      firstName: 'Charlene',
      lastName: 'Lopez',
      email: 'charleneblopez@dayrep.com',
      status: StatusEnum.INACTIVE,
    },
    {
      id: uuid(),
      firstName: 'Phyllis',
      lastName: 'Cheek',
      email: 'phyllisscheek@jourrapide.com',
      status: StatusEnum.PENDING,
      phone: '276-766-3146',
    },
    {
      id: uuid(),
      firstName: 'Patrick',
      lastName: 'Ware',
      email: 'patrickeware@jourrapide.com',
      status: StatusEnum.ACTIVE,
      phone: '512-824-3779',
    },
  ] as Array<Customer>;
}